# data.py

peliculas = [
    {
        "id": 1,
        "nombre": "Avengers: Endgame",
        "genero": "Acción",
        "rating": 9.4,
        "vistas": False,
        "region": "Perú",
        "anio": 2019,
        "duracion": 181,
        "plataforma": "Netflix",
        "likes": 9800
    },
    {
        "id": 2,
        "nombre": "Titanic",
        "genero": "Romance",
        "rating": 8.7,
        "vistas": True,
        "region": "Perú",
        "anio": 1997,
        "duracion": 195,
        "plataforma": "Disney+",
        "likes": 8700
    },
    {
        "id": 3,
        "nombre": "Batman",
        "genero": "Acción",
        "rating": 9.8,
        "vistas": False,
        "region": "Perú",
        "anio": 2022,
        "duracion": 176,
        "plataforma": "HBO Max",
        "likes": 10200
    },
    {
        "id": 4,
        "nombre": "The Notebook",
        "genero": "Romance",
        "rating": 7.5,
        "vistas": False,
        "region": "USA",
        "anio": 2004,
        "duracion": 123,
        "plataforma": "Netflix",
        "likes": 4300
    },
    {
        "id": 5,
        "nombre": "John Wick",
        "genero": "Acción",
        "rating": 9.1,
        "vistas": False,
        "region": "Perú",
        "anio": 2014,
        "duracion": 101,
        "plataforma": "Prime Video",
        "likes": 9200
    },
    {
        "id": 6,
        "nombre": "Interstellar",
        "genero": "Ciencia Ficción",
        "rating": 9.9,
        "vistas": False,
        "region": "Perú",
        "anio": 2014,
        "duracion": 169,
        "plataforma": "Prime Video",
        "likes": 15000
    },
    {
        "id": 7,
        "nombre": "Toy Story",
        "genero": "Animación",
        "rating": 8.3,
        "vistas": True,
        "region": "Perú",
        "anio": 1995,
        "duracion": 81,
        "plataforma": "Disney+",
        "likes": 6700
    },
    {
        "id": 8,
        "nombre": "Spider-Man: No Way Home",
        "genero": "Acción",
        "rating": 9.5,
        "vistas": False,
        "region": "Perú",
        "anio": 2021,
        "duracion": 148,
        "plataforma": "Netflix",
        "likes": 12000
    },
    {
        "id": 9,
        "nombre": "Coco",
        "genero": "Animación",
        "rating": 8.9,
        "vistas": False,
        "region": "México",
        "anio": 2017,
        "duracion": 105,
        "plataforma": "Disney+",
        "likes": 8800
    },
    {
        "id": 10,
        "nombre": "Inception",
        "genero": "Ciencia Ficción",
        "rating": 9.6,
        "vistas": False,
        "region": "Perú",
        "anio": 2010,
        "duracion": 148,
        "plataforma": "Netflix",
        "likes": 13400
    },
    {
        "id": 11,
        "nombre": "Frozen",
        "genero": "Animación",
        "rating": 7.9,
        "vistas": True,
        "region": "Chile",
        "anio": 2013,
        "duracion": 102,
        "plataforma": "Disney+",
        "likes": 7600
    },
    {
        "id": 12,
        "nombre": "La La Land",
        "genero": "Musical",
        "rating": 8.4,
        "vistas": False,
        "region": "USA",
        "anio": 2016,
        "duracion": 128,
        "plataforma": "Netflix",
        "likes": 5900
    },
    {
        "id": 13,
        "nombre": "Parasite",
        "genero": "Drama",
        "rating": 9.3,
        "vistas": False,
        "region": "Corea",
        "anio": 2019,
        "duracion": 132,
        "plataforma": "HBO Max",
        "likes": 9700
    },
    {
        "id": 14,
        "nombre": "The Conjuring",
        "genero": "Terror",
        "rating": 8.1,
        "vistas": False,
        "region": "Perú",
        "anio": 2013,
        "duracion": 112,
        "plataforma": "Prime Video",
        "likes": 6800
    },
    {
        "id": 15,
        "nombre": "Shrek",
        "genero": "Animación",
        "rating": 8.8,
        "vistas": True,
        "region": "Perú",
        "anio": 2001,
        "duracion": 90,
        "plataforma": "Netflix",
        "likes": 9100
    }
]